XxlStore/Models/Cart.cs
namespace XxlStore.Models
{
    public class Cart : Father
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();
        
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines
            .Where(p => p.Product.Id == product.Id)
            .FirstOrDefault();
            if (line == null) {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            } else {
                line.Quantity += quantity;
            }
        }
        
        public virtual void RemoveLine(Product product) =>
            Lines.RemoveAll(l => l.Product.Id == product.Id);
        
        public double ComputeTotalValue() =>
            Lines.Sum(e => e.Product.DiscountPrice * e.Quantity);
        
        public virtual void Clear() => Lines.Clear();
    }
    
    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; } = new();
        public int Quantity { get; set; }
    }
}

XxlStore/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using System.Net.Sockets;
using XxlStore.Models;

namespace XxlStore.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        private JsonResult setOrChange(string id, string qty, bool? isInCart, Action<string, TOrder, OrderLine> Act)
        {
            InitShopData(OrderLoad.PickCurrent);

            if (Bucket.Order == null) Bucket.Order = CreateOrder(false);
            var order = Bucket.Order;

            if (!Utils.IsValidObjectId(id)) return new JsonResult(new { }); // null;
            TWareItem I = domain.WareItems.ById(new ObjectId(id));
            if (I == null) return new JsonResult(new { }); //null; // no such ware!

            OrderLine L = order.FindOrderLine(I);
            if (L == null) {
                L = new OrderLine(I, I.MainPack, 0);
                order.Lines.Add(L);
            }
            //L.UpdatePriceAndDiscount(Bucket);

            var Item = L.ItemRef.Value;
            if (!Item.PublishedExt || Item.FlagSoldOut || Item.mPrice <= 0) {
                L.PackQuantity = 0.0;
            } else {
                Act(qty, order, L);
            }

            order.CalcRequired();
            order.CalcTotals();
            order.Save(CRMSync.NotNeeded);

            bool IsInCart = isInCart ?? false;
            return new JsonResult(
            new OrderJS(order, IsInCart,
                    IsInCart ? RenderPartialViewToString(null, "CartTable", new CartTableModel(Bucket, IsInCart, true, MLSUse), VBSetter, Url.ActionContext, HttpContext) : null,
                Bucket));
        }

        [HttpPost]
        public JsonResult set(string id, string qty, bool? isInCart = null)
        {
            return setOrChange(id, qty, isInCart, setQty);
        }

        public IActionResult Create()
        {
            //if()

            //Cart cart = new Cart();
            //model.CreatedDate = DateTime.Now;

            return View("Edit");
        }
    }
}

XxlStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using XxlStore.Infrastructure;
using XxlStore.Models;

namespace XxlStore.Pages
{
    public class CartModel : PageModel
    {

        IEnumerable<Product> productSource = Data.MainDomain.ExistingTovars;

        public CartModel(Cart cartService)
        {
            Cart = cartService;
        }
        public Cart? Cart { get; set; }
        public string ReturnUrl { get; set; } = "/";
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(string idAsString, string returnUrl)
        {
            Product? product = productSource.FirstOrDefault(p => p.IdAsString == idAsString);
            if (product != null) {
                Cart.AddItem(product, 1);
            }
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(string id, string returnUrl)
        {
            Cart.RemoveLine(Cart.Lines.First(cl =>
            cl.Product.IdAsString == id).Product);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

XxlStore/Pages/Completed.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XxlStore.Pages
{
    public class CompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

XxlStore/Pages/_CartLayout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XxlStore.Pages
{
    public class _CartLayoutModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

XxlStore/Pages/_ViewImports.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XxlStore.Pages
{
    public class _ViewImportsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

XxlStore/Pages/_ViewStart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace XxlStore.Pages
{
    public class _ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

XxlStore/Pages/Cart.cshtml
@page
@model CartModel
<h2>Ваша корзина</h2>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Количество</th>
            <th>Наименование товара</th>
            <th class="text-right">Цена</th>
            <th class="text-right">Цена общая</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model?.Cart?.Lines ?? Enumerable.Empty<CartLine>()) {
            <tr>
                <td class="text-center">@line.Quantity</td>
                <td class="text-left">@line.Product.Name</td>
                <td class="text-right">@line.Product.DiscountPrice.ToString("c")</td>
                <td class="text-right">
                    @((line.Quantity * line.Product.DiscountPrice).ToString("c"))
                </td>
                <td class="text-center">
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="id"
                               value="@line.Product.IdAsString" />
                        <input type="hidden" name="returnUrl"
                               value="@Model?.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">
                            Удалить
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="text-right">Всего:</td>
            <td class="text-right">
                @Model?.Cart?.ComputeTotalValue().ToString("c")
            </td>
        </tr>
    </tfoot>
</table>
<div class="text-center">
    <a class="btn btn-primary" href="@Model?.ReturnUrl">Прподолжить покупки</a>
    @if(Model?.Cart?.Lines.Count() > 0){
        <a class="btn btn-primary" asp-action="Checkout" asp-controller="Order">Оформить заказ</a>
    }
</div>

XxlStore/Pages/Completed.cshtml
@page

<div class="text-center">
    <h2>Спасибо!</h2>
    <p>Ваш заказ #@OrderId</p>
    <p>Мы свяжемся с Вами</p>
    <a class="btn btn-primary" asp-controller="Home">Вернуться в магазин</a>
</div>
@functions {
    [BindProperty(SupportsGet = true)]
    public string? OrderId { get; set; }
}

XxlStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Корзина</title>
    <link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Мир часов</div>
                <div class="col-6 navbar-text text-end">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>